[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = 'compressed_sensing'
description = 'Symbolic regression via compressed sensing: a tutorial'
readme = "README.md"
authors = [
    { name = "Emre Ahmetcik" },
    { name = "Angelo Ziletti" },
    { name = "Runhai Ouyang" },
    { name = "Luigi Sbailò" },
    { name = "Matthias Scheffler" },
    { name = "Luca M. Ghiringhelli" }
]
dynamic = ["version"]
license = { text = "Apache-2.0" }
requires-python = ">=3.9"
dependencies = [
    'pandas',
    'matplotlib',
    'scikit-learn',
    'bokeh',
    'ase',
    'numpy',
    'colorcet',
    'jupyter_jsmol==2021.3.0',
    'plotly'
]

[project.urls]
homepage = "https://nomad-lab.eu/"
repository = "https://gitlab.mpcdf.mpg.de/nomad-lab/analytics-compressed-sensing"

[project.optional-dependencies]
dev = [
    'pytest',
    'nbmake'
]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.setuptools_scm]
